{% set python_min = '3.10' %}
{% set name = "nzgeom" %}
{% set version = "0.1.6" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/nzgeom-{{ version }}.tar.gz
  sha256: a6eb0272dfe7a9095fa5ecde24e100e699e63a054df98887046eaa4983ccac03

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv
  number: 1

requirements:
  host:
    - pip
    - python {{ python_min }}
  run:
    - geopandas
    - python >={{ python_min }}

test:
  imports:
    - nzgeom
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/Timothy-W-Hilton/NZ_geometries
  summary: provide geospatial geometry for NZ coastlines and administrative regions
  license: MIT
  license_file: LICENSE.txt

extra:
  recipe-maintainers:
    - Timothy-W-Hilton
